var mongoose = require('mongoose')
var Schema = mongoose.Schema

var studentSchema = new Schema({
  "type": { type: String, default: 'student'},
  attributes: {
    "ucid": { type: Number },
    "first-name": { type: String },
    "last-name": { type: String },
    "major": { type: String },
    "start-date": { type: Date },
    "ethnicity": { type: String },
    "highshool-name": { type: String },
    "is-sda": { type: Boolean },
    "bgcheck-date": { type: Date },
    "gpa": [ Number ],
    "prov-autobiography": { type: Boolean },
    "prov-educ125": { type: String },
    "prov-application": { type: Boolean },
    "prov-observation-hours": { type: Number },
    "prov-speech-hearing": { type: Boolean },
    "prov-myersbriggs": { type: Boolean },
    "prov-ref-1": { type: Boolean },
    "prov-ref-2": { type: Boolean },
    "prov-ref-3": { type: Boolean },
    "prov-felonstatement": { type: Date },
    "prov-tpcapproval": { type: Date },
    "prov-comments": { type: String },
    "DiversityOBHRS": { type: Boolean },
    "cand-application": { type: Boolean },
    "cand-interview": { type: Boolean },
    "cand-portfolio": { type: Boolean },
    "cand-recommendation": { type: Date },
    "cand-felonystatement": { type: Date },
    "cand-tpcapproval": { type: Date },
    "cand-philosophyhrs": { type: Number },
    "cand-educ218": { type: String },
    "cand-educ225": { type: String },
    "cand-comments": { type: String },
    "cand-ppstreading": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "cand-ppstwriting": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "cand-ppstmathematics": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "cand-corereading": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "cand-corewriting": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "cand-coremathematics": [{ DateTaken: { type: Date }, Score: { type: Number } }],
    "pre-studteachap": { type: Boolean },
    "pre-recommendation": { type: Boolean },
    "pre-bgcheck": { type: Boolean },
    "pre-one-source-sub": { type: Boolean },
    "pre-workrequest": { type: Boolean },
    "pre-physical-tb-test": { type: Boolean },
    "pre-portfolio": { type: Boolean },
    "pre-presession-st": { type: Boolean },
    "pre-learingtheory": { type: Boolean },
    "pre-gensec": { type: Boolean },
    "pre-felonystatement": { type: Date },
    "pre-studentteaching-date": { type: Date },
    "pre-tcp-approval": { type: Date },
    "pre-spedhrs": { type: Number },
    "pre-educ345": { type: String },
    "pre-educ346": { type: String },
    "pre-educ356": { type: String },
    "pre-comments": { type: String },
    "st-portfolio": { type: Boolean },
    "st-resume": { type: Boolean },
    "st-felonystatement": { type: Date },
    "st-startdate": { type: Date },
    "st-graddate": { type: Date },
    "st-init-cert-date": { type: Date },
    "st-cert-app": { type: Boolean },
    "stu-praxII-name": { type: String },
    "stu-praxII-datetaken": { type: Date },
    "stu-praxII-score": { type: Number },
    "stu-fs-schoolname": { type: String },
    "stu-fs-teachername": { type: String },
    "stu-fs-dates": { type: Date },
    "stu-fs-contract": { type: Boolean },
    "stu-fs-practicum": { type: Boolean },
    "stu-fs-cteval": { type: Boolean },
    "stu-fs-ctrq": { type: Boolean },
    "stu-ss-schoolname": { type: String },
    "stu-ss-teachername": { type: String },
    "stu-ss-dates": { type: Date },
    "stu-ss-contract": { type: Boolean },
    "stu-ss-practicum": { type: Boolean },
    "stu-ss-cteval": { type: Boolean },
    "stu-ss-ctrq": { type: Boolean }

  }
})
module.exports = mongoose.model('Student', studentSchema)
