var mongoose = require('mongoose')
var Schema = mongoose.Schema

var studentSchema = new Schema({
  "type"                      : { type: String, default: 'student'},
  attributes: {
    "ucid"                    : { type: Number },
    "first-name"              : { type: String },
    "last-name"               : { type: String },
    "major"                   : { type: String },
    "start-date"              : { type: Date },
    "ethnicity"               : { type: String },
    "highshool-name"          : { type: String },
    "is-sda"                  : { type: Boolean },
    "bgcheck-date"            : { type: Date },
    "gpa"                     : [],
    "prov-autobiography"      : { type: Boolean },
    "prov-educ125"            : { type: String },
    "prov-application"        : { type: Boolean },
    "prov-observation-hours"  : { type: Number },
    "prov-speech-hearing"     : { type: Boolean },
    "prov-myersbriggs"        : { type: Boolean },
    "prov-ref-1"              : { type: Boolean },
    "prov-ref-2"              : { type: Boolean },
    "prov-ref-3"              : { type: Boolean },
    "prov-felonstatement"     : { type: Date },
    "prov-tpcapproval"        : { type: Date },
    "prov-comments"           : { type: String },
    "DiversityOBHRS"          : { type: Boolean },
    "cand-application"        : { type: Boolean },
    "cand-interview"          : { type: Boolean },
    "cand-portfolio"          : { type: Boolean },
    "cand-recommendation"     : { type: Date },
    "cand-felonystatement"    : { type: Date },
    "cand-tpcapproval"        : { type: Date },
    "cand-philosophyhrs"      : { type: Number },
    "cand-educ218"            : { type: String },
    "cand-educ225"            : { type: String },
    "cand-comments"           : { type: String },
    "cand-tests"              : { Array },
    "pre-studteachap"         : { type: Boolean },
    "pre-recommendation"      : { type: Boolean },
    "pre-bgcheck"             : { type: Boolean },
    "pre-one-source-sub"      : { type: Boolean },
    "pre-workrequest"         : { type: Boolean },
    "pre-physical-tb-test"    : { type: Boolean },
    "pre-portfolio"           : { type: Boolean },
    "pre-presession-st"       : { type: Boolean },
    "pre-learingtheory"       : { type: Boolean },
    "pre-gensec"              : { type: Boolean },
    "pre-felonystatement"     : { type: Date },
    "pre-studentteaching-date": { type: Date },
    "pre-tcp-approval"        : { type: Date },
    "pre-spedhrs"             : { type: Number },
    "pre-educ345"             : { type: String },
    "pre-educ346"             : { type: String },
    "pre-educ356"             : { type: String },
    "pre-comments"            : { type: String },
    "st-portfolio"            : { type: Boolean },
    "st-resume"               : { type: Boolean },
    "st-felonystatement"      : { type: Date },
    "st-startdate"            : { type: Date },
    "st-graddate"             : { type: Date },
    "st-init-cert-date"       : { type: Date },
    "st-cert-app"             : { type: Boolean },
    "st-tests"                : { type: Array },
    "st-teaching"             : {type: Array }
  }
})
mongoose.model('Student', studentSchema)
